language: node_js
node_js:
  - 4
  - 6
  - 8
  - 9

sudo: false
before_install:
  - git fetch --unshallow
  - curl -L https://unpkg.com/@pnpm/self-installer@1.23.2 | node
  # Testing whether pnpm can upgrade itself
  - pnpm i -g pnpm@next
  - pnpm -v
install:
  - pnpm i --prefix .scripts/self-installer
  - pnpm i
script:
  - /bin/bash lint-commits.sh
  - ./node_modules/.bin/commitlint --from=$TRAVIS_COMMIT
  - npm test --prefix .scripts/self-installer
  - npm t
env:
  global:
    - CC=clang CXX=clang++ npm_config_clang=1
    - GIT_NAME: Travis CI
    - GIT_EMAIL: nobody@nobody.org
    - GITHUB_REPO: pnpm/pnpm
notifications:
  email: false
